# Generated by Django 3.2.19 on 2023-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='emotion',
            field=models.CharField(default='', max_length=5),
        ),
    ]
